[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma generate && npx prisma db push --accept-data-loss && npm start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
